EduEventHub/PresentationLayer/Areas/Admin/Controllers/SpeakerController.cs
using DataLayer.Data;
using DataLayer.Models;
using DataLayer.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PresentationLayer.Helpers;
using PresentationLayer.ViewModels;
using System.Threading.Tasks;

namespace PresentationLayer.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = ("SuperAdmin"))]
    public class SpeakerController : Controller
    {
        private readonly IRepository<Speaker> _repository;
        
        public SpeakerController(IRepository<Speaker> speakerRepository)
        {
            _repository = speakerRepository;
        }

        public async Task<IActionResult> Index(PageFiltesVM filter)
        {
            var items = await _repository.GetAllAsync(skip: filter.SkipNumber, take:filter.PageSize);
            var count = await _repository.CountAsync();
            var data = new ModelsWithPaginationVM<Speaker>()
            {
                Items = items.ToList(),
                Pagination = new PaginationVM
                {
                    PageNumber = filter.PageNumber ?? 0,
                    PageSize = filter.PageSize ?? 0,
                    TotalCount = count
                }
            };
            return View(data);
        }

        public IActionResult Create()
        {
            return View(new Speaker());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Speaker speaker, IFormFile ImgPath)
        {
            if(!ModelState.IsValid)
            {
                return View(speaker);
            }

            if (ImgPath != null && ImgPath.Length > 0)
            {
                string fileName = FileHelper.CreateFileName(ImgPath.FileName);
                var path = "assets\\images\\speakers";
                string filePath = FileHelper.GetFilePath(fileName, "wwwroot\\" + path);
                await FileHelper.UploadFile(filePath, ImgPath);
                speaker.ImgPath = path+'\\'+fileName;
            }
            else
            {
                ModelState.AddModelError("ImgPath", "Image is required.");
                return View(speaker);
            }

            await _repository.AddAsync(speaker);

            TempData["SuccessMessage"] = "Speaker created successfully.";

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {
            var data = await _repository.GetOneAsync(x => x.Id == id, includeChain: e => e.Include(q => q.EventContents)
                                                                                          .ThenInclude(q => q.EventAgenda)
                                                                                          .ThenInclude(q => q.Event)
                                                                                    );
            if (data == null)
                return NotFound();

            var events = data.EventContents.Select(x => x.EventAgenda.Event).Distinct().ToList();
            ViewBag.Events = events;
            return View(data) ;
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Speaker speaker, IFormFile ImgPath)
        {
            ModelState.Remove("ImgPath");
            if (!ModelState.IsValid)
            {
                return View(speaker);
            }

            var oldData = await _repository.GetOneAsync(x => x.Id  == speaker.Id, AsNoTracking:true);
            if (oldData == null)
            {
                return NotFound();
            }

            if (ImgPath != null && ImgPath.Length > 0)
            {
                string fileName = FileHelper.CreateFileName(ImgPath.FileName);
                var path = "assets\\images\\speakers";
                string filePath = FileHelper.GetFilePath(fileName, "wwwroot\\"+path);
                await FileHelper.UploadFile(filePath, ImgPath);
                speaker.ImgPath = path + '\\' + fileName;
            }
            else
            {
                speaker.ImgPath = oldData.ImgPath;
            }

            await _repository.UpdateAsync(speaker);
            TempData["SuccessMessage"] = "Speaker Updated successfully.";

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var data = await _repository.GetOneAsync(x => x.Id == id);
            if (data == null)
                return NotFound();
            await _repository.DeleteAsync(x => x.Id == id);
            TempData["SuccessMessage"] = "Speaker Deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

    }
}

EduEventHub/PresentationLayer/Areas/Customer/Controllers/SpeakerController.cs
using DataLayer.Models;
using DataLayer.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PresentationLayer.ViewModels;
using System.Threading.Tasks;

namespace PresentationLayer.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class SpeakerController : Controller
    {
        private readonly IRepository<Speaker> _repository;
        public SpeakerController(IRepository<Speaker> repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _repository.GetAllAsync(orderBy: q => q.OrderByDescending(x => x.Id));
            return View(data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var speaker = await _repository.GetOneAsync(x => x.Id == id, 
                                                includeChain: q => q.Include(e => e.EventContents)
                                                               .ThenInclude(ec => ec.EventAgenda)
                                                               .ThenInclude(a => a.Event)
                                                               .Include(q => q.SocialMedias)
                                            );
            if (speaker == null)
            {
                return NotFound();
            }

            var events = speaker.EventContents.Select(ec => ec.EventAgenda.Event).Distinct().ToList();

            var data = new SpeakerDetailsViewModel
            {
                Speaker = speaker,
                Events = events
            };

            return View(data);
        }
    }
}

EduEventHub/PresentationLayer/Areas/Customer/Views/Speaker/Details.cshtml
@model SpeakerDetailsViewModel


<section class="page-title bg-title overlay-dark">
	<div class="container">
		<div class="row">
			<div class="col-12 text-center">
				<div class="title">
					<h3>Speaker Details</h3>
				</div>
				<ol class="breadcrumb p-0 m-0">
					<li class="breadcrumb-item"><a href="index.html">Home</a></li>
					<li class="breadcrumb-item active">Speaker Details</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<!--====  End of Page Title  ====-->


<section class="section single-speaker">
	<div class="container">
		<div class="block">
			<div class="row">
				<div class="col-lg-5 col-md-6 align-self-md-center">
					<div class="image-block">
						<img src="~/@Model.Speaker.ImgPath" class="img-fluid" alt="speaker">
					</div>
				</div>
				<div class="col-lg-7 col-md-6 align-self-center">
					<div class="content-block">
						<div class="name">
							<h3>@Model.Speaker.Name</h3>
						</div>
						<div class="profession">
							<p>@Model.Speaker.Specialization</p>
						</div>
						<div class="details">
							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusm tempor incididunt ut labore dolore magna aliqua enim ad minim veniam quis nostrud.laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.
								Duis aute irure dolor in reprehenderit in voluptate velit esse.
								<br>
							</p>
							<p>
								Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
								<br>
								Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur
							</p>
						</div>
						@if (Model.Speaker.SocialMedias.Count != 0)
						{
							<div class="social-profiles">
								<h5>Social Profiles</h5>
								<ul class="list-inline social-list">
									@foreach (var social in Model.Speaker.SocialMedias)
									{
										if (social.Platform == PlatForm.Twitter)
										{
											<li class="list-inline-item">
												<a href="@social.Url"><i class="fa fa-twitter"></i></a>
											</li>
										}
										if (social.Platform == PlatForm.LinkedIn)
										{
											<li class="list-inline-item">
												<a href="@social.Url"><i class="fa fa-linkedin"></i></a>
											</li>
										}
										if (social.Platform == PlatForm.Facebook)
										{
											<li class="list-inline-item">
												<a href="@social.Url"><i class="fa fa-facebook"></i></a>
											</li>
										}
										if (social.Platform == PlatForm.YouTube)
										{
											<li class="list-inline-item">
												<a href="@social.Url"><i class="fa fa-youtube"></i></a>
											</li>
										}

										if (social.Platform == PlatForm.Instagram)
										{
											<li class="list-inline-item">
												<a href="@social.Url"><i class="fa fa-instagram"></i></a>
											</li>
										}


									}
								</ul>
							</div>
						}
					</div>
				</div>
			</div>
		</div>

	</div>
</section>

<section class="section schedule" style="padding-top:0;">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="section-title">
					<h3>Speaker <span class="alternate"> Events</span></h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusm tempor incididunt ut labore</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				



				<div class="schedule-contents bg-schedule">
					<div class="tab-content" id="pills-tabContent">
						@{
							var j = 0;
						}

							<div class="tab-pane fade show active schedule-item">
								<!-- Headings -->
								<ul class="m-0 p-0">
									<li class="headings">
										<div class="time">Date</div>
										<div class="speaker">Event</div>
										<div class="subject">Subject</div>
									</li>

									@foreach (var sEvent in Model.Events)
									{
										<!-- Schedule Details -->
										<li class="schedule-details">
											<div class="block">
												<a asp-controller="Event" asp-action="Details" asp-route-id="@sEvent.Id">
												<!-- time -->
												<div class="time">
													<i class="fa fa-clock-o"></i>
													<span class="time">@sEvent.StartDate.ToString("dd MMMM yyyy")</span>
												</div>
												<!-- Speaker -->
												<div class="speaker" style="text-align:center">
													<img src="~/@sEvent.ImgPath" alt="speaker-thumb-one" style="width:65px; height:65px;">
													<span class="name">@sEvent.Title</span>
													
												</div>
												<!-- Subject -->
												<div class="subject" style="width:45%;">@sEvent.Description</div>
												</a>
											</div>
										</li>

									}
								</ul>
							</div>

		
					</div>
				</div>

			</div>
		</div>
	</div>
</section>

EduEventHub/PresentationLayer/Areas/Customer/Views/Speaker/Index.cshtml
@model IEnumerable<Speaker>

<section class="page-title bg-title overlay-dark">
	<div class="container">
		<div class="row">
			<div class="col-12 text-center">
				<div class="title">
					<h3>Speakers</h3>
				</div>
				<ol class="breadcrumb p-0 m-0">
					<li class="breadcrumb-item"><a href="/">Home</a></li>
					<li class="breadcrumb-item active">Speakers</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<section class="section speakers white">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Section Title -->
				<div class="section-title">
					<h3>Our <span class="alternate">Speakers!</span></h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusm tempor incididunt ut labore</p>
				</div>
			</div>
		</div>
		<div class="row">

			@foreach (var item in Model)
			{
				<div class="col-lg-3 col-md-4 col-sm-6">
					<!-- Speaker 1 -->
					<div class="speaker-item">
						<div class="image">
							<a asp-controller="Speaker" asp-action="Details" asp-route-id="@item.Id">
								<img src="~/@item.ImgPath" alt="speaker" class="img-fluid" style="height:244.984px">
							</a>
							<div class="primary-overlay"></div>
							<div class="socials">
								<ul class="list-inline">
									<li class="list-inline-item"><a href="~/#"><i class="fa fa-facebook"></i></a></li>
									<li class="list-inline-item"><a href="~/#"><i class="fa fa-twitter"></i></a></li>
									<li class="list-inline-item"><a href="~/#"><i class="fa fa-linkedin"></i></a></li>
									<li class="list-inline-item"><a href="~/#"><i class="fa fa-pinterest"></i></a></li>
								</ul>
							</div>
						</div>
						<div class="content text-center">
							<a asp-controller="Speaker" asp-action="Details" asp-route-id="@item.Id">
								<h5>@item.Name</h5>
								<p>@item.Specialization</p>
							</a>
						</div>
					</div>
				</div>
			}

		</div>
	</div>
</section>